baseURL = 'https://jinah95.github.io/hugo-docs-test/'
languageCode = 'ko-kr'          # 한국어 설정
title = '가이드 문서'     # 사이트 타이틀
theme = 'hugo-book'             # 🎯 다운받은 테마 이름 지정!

[params]
  BookSection = 'docs'
  # hugo-book 테마 고유의 옵션들 설정
  # BookLogo = 'images/logo.png'  # 로고 이미지 경로 (선택)
  BookMenuBundle = true         # 메뉴 구조 자동 바인딩 - 중첩 파일 트리 구조 그대로 사이드바 랜더링 위해 false

# 빌드 시 자바스크립트/데이터 파일 뒤에 고유 해시(지문)를 붙여 브라우저 캐시를 무력화합니다.
[configureFingerprint]
  enabled = true

[action]
  disablePathToLower = false  

# js, scss 에는 난수화가 가능하지만, HTML파일 자체는 브라우저 자체 캐싱을 꺾기가 어려움 - 파일명 자체가 경로기 때문에
[params]
  bookFastNavigation = false