backend:
  name: github
  repo: jinah95/hugo-docs-test
  branch: main
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: "docs"
    label: "가이드 문서 관리"
    folder: "content/docs"
    create: true
    # 트리 구조(중첩 경로) 활성화
    type: "nested"
    nested:
      depth: 5 # 최대 5단계 하위 폴더까지 트리로 표시하겠다는 설정
    path: "{{dir}}/{{slug}}"
    slug: "{{slug}}"
    extension: "md"
    format: "toml-frontmatter"
    meta: { path: { widget: "hidden", index: 0 } }
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일자", name: "date", widget: "datetime" }
      - { label: "본문 내용", name: "body", widget: "markdown" }
